robot.name=MadaraV3
robot.classname=TriStateRobots.MadaraV3
robot.author.name=Kaijuu
robot.description=Uchiha Madara - Adaptive Combat System
robot.webpage=https://github.com/oKaijuu/ROBOCODE-2026-IFSC-ADS
robocode.version=1.0
robot.java.source.included=true